"""edit location field

Revision ID: 0b41111e6a2c
Revises: 15cc572b91c0
Create Date: 2025-05-06 00:13:43.189155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b41111e6a2c"
down_revision: Union[str, None] = "15cc572b91c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotels", sa.Column("location", sa.String(), nullable=False))
    op.drop_column("hotels", "locaton")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels",
        sa.Column("locaton", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("hotels", "location")
    # ### end Alembic commands ###
