"""first attempt make email column unique

Revision ID: f6d5fadc6446
Revises: d1a5d15b49ce
Create Date: 2025-05-16 00:04:52.540499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6d5fadc6446"
down_revision: Union[str, None] = "d1a5d15b49ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
